//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Installer.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Installer.Localization.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Thank you for installing TONX! 的本地化字符串。
        /// </summary>
        public static string AllDoneTips {
            get {
                return ResourceManager.GetString("AllDoneTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following mods will be removed after continuing 的本地化字符串。
        /// </summary>
        public static string DeleteUnusedPluginsWarning {
            get {
                return ResourceManager.GetString("DeleteUnusedPluginsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to downloading BepInEx 的本地化字符串。
        /// </summary>
        public static string Download_BepInEx_Failed {
            get {
                return ResourceManager.GetString("Download.BepInEx.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to downloading TONX 的本地化字符串。
        /// </summary>
        public static string Download_TONX_Failed {
            get {
                return ResourceManager.GetString("Download.TONX.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requesting download TONX 的本地化字符串。
        /// </summary>
        public static string Download_TONX_Requesting {
            get {
                return ResourceManager.GetString("Download.TONX.Requesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The version is relatively backward 的本地化字符串。
        /// </summary>
        public static string DownloadChannel_Gitee_Desc {
            get {
                return ResourceManager.GetString("DownloadChannel.Gitee.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stable, Recommended 的本地化字符串。
        /// </summary>
        public static string DownloadChannel_Github_Desc {
            get {
                return ResourceManager.GetString("DownloadChannel.Github.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to delete redundant files 的本地化字符串。
        /// </summary>
        public static string FailedTo_Cleanup {
            get {
                return ResourceManager.GetString("FailedTo.Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to extracting downloaded files 的本地化字符串。
        /// </summary>
        public static string FailedTo_Extracting {
            get {
                return ResourceManager.GetString("FailedTo.Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Folder 的本地化字符串。
        /// </summary>
        public static string GameFolder {
            get {
                return ResourceManager.GetString("GameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a valid Among Us folder used to install 的本地化字符串。
        /// </summary>
        public static string GameFolderEnterBoxPlaceholderText {
            get {
                return ResourceManager.GetString("GameFolderEnterBoxPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BepInEx Installed 的本地化字符串。
        /// </summary>
        public static string Install_BepInEx_Done {
            get {
                return ResourceManager.GetString("Install.BepInEx.Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading BepInEx 的本地化字符串。
        /// </summary>
        public static string Install_BepInEx_Downloading {
            get {
                return ResourceManager.GetString("Install.BepInEx.Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting BepInEx to game directory 的本地化字符串。
        /// </summary>
        public static string Install_BepInEx_Extracting {
            get {
                return ResourceManager.GetString("Install.BepInEx.Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install BepInEx: Pending 的本地化字符串。
        /// </summary>
        public static string Install_BepInEx_Pending {
            get {
                return ResourceManager.GetString("Install.BepInEx.Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TONX Installed 的本地化字符串。
        /// </summary>
        public static string Install_TONX_Done {
            get {
                return ResourceManager.GetString("Install.TONX.Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading TONX 的本地化字符串。
        /// </summary>
        public static string Install_TONX_Downloading {
            get {
                return ResourceManager.GetString("Install.TONX.Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install TONX: Pending 的本地化字符串。
        /// </summary>
        public static string Install_TONX_Pending {
            get {
                return ResourceManager.GetString("Install.TONX.Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Among Us game folder 的本地化字符串。
        /// </summary>
        public static string InvalidGameFolderTips {
            get {
                return ResourceManager.GetString("InvalidGameFolderTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Step 的本地化字符串。
        /// </summary>
        public static string LastStep {
            get {
                return ResourceManager.GetString("LastStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Step 的本地化字符串。
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please try again using another download channel 的本地化字符串。
        /// </summary>
        public static string PlzTryAgainUsingOtherDownlodChennel {
            get {
                return ResourceManager.GetString("PlzTryAgainUsingOtherDownlodChennel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please try again with Administrator access 的本地化字符串。
        /// </summary>
        public static string PlzTryAgainWithUAC {
            get {
                return ResourceManager.GetString("PlzTryAgainWithUAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download channel 的本地化字符串。
        /// </summary>
        public static string SelectDownloadChennel {
            get {
                return ResourceManager.GetString("SelectDownloadChennel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TONX Installer 的本地化字符串。
        /// </summary>
        public static string TownOfNextInstaller {
            get {
                return ResourceManager.GetString("TownOfNextInstaller", resourceCulture);
            }
        }
    }
}
